language: node_js
sudo: false
os: osx
node_js:
  - 8
install:
  - sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "INSERT INTO access VALUES ('kTCCServiceAccessibility','com.apple.Terminal',0,1,1,NULL,NULL);"
  - yarn
script:
  - yarn eslint
  - yarn flow
  - yarn test
