image:
- Visual Studio 2017

# Test agains
environment:
  matrix:
    - nodejs_version: '8'
  access_token:
    secure: xl/DOD+43yfh+yw5zLcYazakf8AjgD/1XkDiekFwPY/oBPruovwJQU3n/Lp8h7jE

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Install scripts--runs after repo cloning
install:
  # Install the latest stable version of Node
  - ps: Install-Product node $env:nodejs_version x64
  - set PATH=%APPDATA%\yarn;%PATH%
  - yarn
  - node ./scripts/screenshot.js screenshot_test/after-yarn.png
  - ps: ./scripts/install-and-link-packages.ps1
  - node ./scripts/screenshot.js screenshot_test/after-install-and-link.png
  - ps: ./scripts/windows-ci-desktop-layout.ps1
  - node ./scripts/screenshot.js screenshot_test/after-windows-ci.png

# Disable automatic builds
build: off

# Post-install test scripts
test_script:
  # Output debugging info
  - node --version
  - yarn --version
  # run tests and run build
  - yarn run eslint
  - node ./scripts/screenshot.js screenshot_test/after-lint.png
  - yarn run flow
  - node ./scripts/screenshot.js screenshot_test/after-flow.png
  - appveyor-retry yarn jest -- --forceExit
  - node ./scripts/screenshot.js screenshot_test/after-jest.png

on_failure:
  - ps: New-Item -ItemType Directory -Force -Path .\test\integration\__image_snapshots\__diff_output__
  - ps: try { Get-ChildItem .\test\integration\__image_snapshots__\__diff_output__\*.png | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name } } catch { echo error }

on_finish:
  - ps: ./scripts/appveyor-update-snapshot.ps1
  - ps: Get-ChildItem .\screenshot_test*.png | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

# Cache node_modules for faster builds
cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules -> package.json
