image:
- Visual Studio 2017

# Test agains
environment:
  matrix:
    - nodejs_version: '8'
  access_token:
    secure: xl/DOD+43yfh+yw5zLcYazakf8AjgD/1XkDiekFwPY/oBPruovwJQU3n/Lp8h7jE

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Install scripts--runs after repo cloning
install:
  # Install the latest stable version of Node
  - ps: Install-Product node $env:nodejs_version x64
  - set PATH=%APPDATA%\yarn;%PATH%
  - yarn
  - rollup -c
  - ps: ./scripts/windows-ci-desktop-layout.ps1

# Disable automatic builds
build: off

# Post-install test scripts
test_script:
  # Output debugging info
  - node --version
  - yarn --version
  # run tests and run build
  - yarn run eslint
  - yarn run flow
  - yarn test unit
  - appveyor-retry yarn test integration --runInBand

on_failure:
  - ps: New-Item -ItemType Directory -Force -Path .\test\integration\__image_snapshots__\__diff_output__
  - ps: Get-ChildItem .\test\integration\__image_snapshots__\__diff_output__\*.png | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

on_finish:
  - ps: ./scripts/appveyor-update-snapshot.ps1

# Cache node_modules for faster builds
cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules -> package.json
