#!/bin/bash

Xvfb :2 >/dev/null 2>/dev/null &
DISPLAY=:2 i3 >/dev/null 2>/dev/null &

if [ "$1" = "-u" ]; then
  DISPLAY=:2 npm run test -- -u
else
  DISPLAY=:2 npm run test
fi

pkill Xvfb >/dev/null 2>/dev/null
