#!/bin/bash


echo 'export PS1="\w # "' >> ~/.bashrc

# Hide Dock
defaults write com.apple.Dock autohide -bool TRUE
killall Dock

# Hide Menu Bar
defaults write NSGlobalDomain _HIHideMenuBar -bool true
killall Finder
